import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const PopinsBold = localFont({
  src: "./fonts/Poppins-Bold.ttf",
  variable: "--font-popin-bold",
  weight: "600 900",
});
const popinRegular = localFont({
  src: "./fonts/Poppins-Regular.ttf",
  variable: "--font-popin-regular",
  weight: "100 500",
});
const Fredoka = localFont({
  src: "./fonts/FredokaOne-Regular.otf",
  variable: "--font-Fredoka-bold",
  weight: "100 900",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${PopinsBold.variable} ${popinRegular.variable} ${Fredoka.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
